// The 10 validation topics — chosen to exercise every category + the core text content-types.
// (Embed-based types — X/IG reactions, interview, trailer — come in a second batch once the
//  embed layer is built; faking them now would risk the legal/quality bar.)
export const TOPICS = [
  { id: "tarantino-ranked", slug: "best-quentin-tarantino-movies-ranked", title: "Best Quentin Tarantino Movies, Ranked", contentType: "ranking list", category: "movies", subcategory: "rankings-lists", primaryKeyword: "best quentin tarantino movies", primaryEntity: "Quentin Tarantino", entities: ["Quentin Tarantino", "Pulp Fiction", "Kill Bill: Volume 1", "Django Unchained", "Inglourious Basterds", "Once Upon a Time in Hollywood", "Reservoir Dogs"] },
  { id: "inception-ending", slug: "inception-ending-explained", title: "Inception Ending Explained", contentType: "explainer", category: "movies", subcategory: "explainers", primaryKeyword: "inception ending explained", primaryEntity: "Inception", entities: ["Inception", "Christopher Nolan", "Leonardo DiCaprio"] },
  { id: "kotfm-review", slug: "killers-of-the-flower-moon-review", title: "Killers of the Flower Moon Review", contentType: "review", category: "reviews", subcategory: "movie-reviews", primaryKeyword: "killers of the flower moon review", primaryEntity: "Killers of the Flower Moon", entities: ["Killers of the Flower Moon", "Martin Scorsese", "Lily Gladstone"] },
  { id: "fallout-review", slug: "fallout-tv-review", title: "Fallout Review", contentType: "review", category: "reviews", subcategory: "tv-reviews", primaryKeyword: "fallout review", primaryEntity: "Fallout (American TV series)", entities: ["Fallout (American TV series)", "Ella Purnell", "Walton Goggins"] },
  { id: "austin-butler", slug: "austin-butler-movies-and-tv-shows", title: "Austin Butler Movies and TV Shows", contentType: "profile", category: "celebrity", subcategory: "profiles-careers", primaryKeyword: "austin butler movies and tv shows", primaryEntity: "Austin Butler", entities: ["Austin Butler", "Elvis (2022 film)", "Dune: Part Two", "The Bikeriders"] },
  { id: "best-scifi-tv", slug: "best-sci-fi-tv-shows-ranked", title: "Best Sci-Fi TV Shows of All Time, Ranked", contentType: "ranking list", category: "tv", subcategory: "rankings-lists", primaryKeyword: "best sci-fi tv shows", primaryEntity: "Battlestar Galactica (2004 TV series)", entities: ["Battlestar Galactica (2004 TV series)", "The Expanse (TV series)", "Black Mirror", "Severance (TV series)", "Westworld (TV series)"] },
  { id: "best-on-max", slug: "best-movies-on-max", title: "The Best Movies on Max Right Now, Ranked", contentType: "streaming guide", category: "streaming", subcategory: "best-of-streaming", primaryKeyword: "best movies on max", provider: "Max", primaryEntity: "The Dark Knight", entities: ["The Dark Knight"] },
  { id: "lotr-where-watch", slug: "where-to-watch-lord-of-the-rings", title: "Where to Watch the Lord of the Rings Movies", contentType: "streaming guide", category: "streaming", subcategory: "where-to-watch", primaryKeyword: "where to watch lord of the rings", primaryEntity: "The Lord of the Rings (film series)", entities: ["The Lord of the Rings (film series)", "The Lord of the Rings: The Fellowship of the Ring", "The Lord of the Rings: The Two Towers", "The Lord of the Rings: The Return of the King"] },
  { id: "barbenheimer", slug: "barbenheimer-explained", title: "Barbenheimer Explained: How Barbie and Oppenheimer Made History", contentType: "explainer", category: "movies", subcategory: "explainers", primaryKeyword: "barbenheimer explained", primaryEntity: "Barbenheimer", entities: ["Barbenheimer", "Barbie (film)", "Oppenheimer (film)"] },
  { id: "sydney-sweeney", slug: "sydney-sweeney-movies-and-tv-shows", title: "Sydney Sweeney Movies and TV Shows", contentType: "profile", category: "celebrity", subcategory: "profiles-careers", primaryKeyword: "sydney sweeney movies and tv shows", primaryEntity: "Sydney Sweeney", entities: ["Sydney Sweeney", "Euphoria (American TV series)", "Anyone but You", "The White Lotus"] },

  // ---- Batch 2: embed niches (tested one-by-one). formatTag drives the niche UI + routing. ----
  { id: "superman-trailer", slug: "superman-2025-trailer-everything-to-know", title: "The Superman Trailer: Everything to Know About James Gunn's Reboot", contentType: "trailer", formatTag: "trailer", category: "movies", subcategory: "trailers", tmdbType: "movie", primaryKeyword: "superman trailer", primaryEntity: "Superman (2025 film)", entities: ["Superman (2025 film)", "James Gunn", "David Corenswet", "Rachel Brosnahan", "Nicholas Hoult"] },
  // Interview niche: youtubeId is a real, captioned, SOLO official interview (transcript-grounded summary + embedded video). Production discovery = searchInterview().
  { id: "pedro-pascal-hot-ones", slug: "pedro-pascal-hot-ones-interview", title: "Pedro Pascal on Hot Ones: What the Star Revealed", contentType: "interview", formatTag: "interview", category: "celebrity", subcategory: "interviews", youtubeId: "zVRwUHbHgt8", primaryKeyword: "pedro pascal hot ones", primaryEntity: "Pedro Pascal", entities: ["Pedro Pascal", "The Last of Us (TV series)", "The Mandalorian"] },
  // Awards niche (winners-list). Winners grounded on the Wikipedia ceremony page (accuracy-critical).
  { id: "oscars-96-winners", slug: "oscars-2024-winners-96th-academy-awards", title: "Oscars 2024 Winners: Oppenheimer Sweeps the 96th Academy Awards", contentType: "awards winners", formatTag: "awards", category: "awards", subcategory: "winners", primaryKeyword: "oscars 2024 winners", primaryEntity: "96th Academy Awards", entities: ["96th Academy Awards", "Oppenheimer (film)", "Christopher Nolan", "Cillian Murphy", "Emma Stone"], angle: "Oppenheimer's seven-win sweep and the night's biggest moments" },
  // Box-office niche (trade-style, number-forward). Figures grounded on TMDB (worldwide+budget) + Wikipedia.
  { id: "barbie-box-office", slug: "barbie-box-office-2023", title: "Barbie Box Office: How Greta Gerwig's Hit Made History", contentType: "box office", formatTag: "box-office", category: "movies", subcategory: "box-office", primaryKeyword: "barbie box office", primaryEntity: "Barbie (film)", entities: ["Barbie (film)", "Greta Gerwig", "Margot Robbie", "Warner Bros."], angle: "Barbie's record-breaking run, the records it set, and what it meant for Warner Bros. and women directors" },
  // Celebrity short-news niche (inverted-pyramid, AP style). Grounded on Wikipedia (documented casting).
  { id: "zendaya-odyssey-news", slug: "zendaya-the-odyssey-christopher-nolan", title: "Zendaya Joins Christopher Nolan's The Odyssey", contentType: "celebrity news", formatTag: "news", category: "celebrity", subcategory: "news", primaryKeyword: "zendaya the odyssey", primaryEntity: "Zendaya", entities: ["Zendaya", "The Odyssey (2026 film)", "Christopher Nolan"], angle: "What Zendaya's casting in Christopher Nolan's epic signals for her career and the film" },
  // Reaction niche: tweetIds are real, public, syndication-verified posts (mixed sentiment). Production discovery will curate higher-follower/critic accounts.
  { id: "superman-reactions", slug: "superman-2025-reactions-what-fans-are-saying", title: "Superman 2025 Reactions: What Critics and Fans Are Saying", contentType: "reaction", formatTag: "reaction", category: "movies", subcategory: "reactions", primaryKeyword: "superman 2025 reactions", primaryEntity: "Superman (2025 film)", entities: ["Superman (2025 film)", "James Gunn", "David Corenswet"], tweetIds: ["1942433712928342354", "1942433464537559241", "1943486116080017514", "1994017424501281227"] },
];
