// The 10 validation topics — chosen to exercise every category + the core text content-types.
// (Embed-based types — X/IG reactions, interview, trailer — come in a second batch once the
//  embed layer is built; faking them now would risk the legal/quality bar.)
export const TOPICS = [
  { id: "tarantino-ranked", slug: "best-quentin-tarantino-movies-ranked", title: "Best Quentin Tarantino Movies, Ranked", contentType: "ranking list", category: "movies", subcategory: "rankings-lists", primaryKeyword: "best quentin tarantino movies", primaryEntity: "Quentin Tarantino", entities: ["Quentin Tarantino", "Pulp Fiction", "Kill Bill: Volume 1", "Django Unchained", "Inglourious Basterds", "Once Upon a Time in Hollywood", "Reservoir Dogs"] },
  { id: "inception-ending", slug: "inception-ending-explained", title: "Inception Ending Explained", contentType: "explainer", category: "movies", subcategory: "explainers", primaryKeyword: "inception ending explained", primaryEntity: "Inception", entities: ["Inception", "Christopher Nolan", "Leonardo DiCaprio"] },
  { id: "kotfm-review", slug: "killers-of-the-flower-moon-review", title: "Killers of the Flower Moon Review", contentType: "review", category: "reviews", subcategory: "movie-reviews", primaryKeyword: "killers of the flower moon review", primaryEntity: "Killers of the Flower Moon", entities: ["Killers of the Flower Moon", "Martin Scorsese", "Lily Gladstone"] },
  { id: "fallout-review", slug: "fallout-tv-review", title: "Fallout Review", contentType: "review", category: "reviews", subcategory: "tv-reviews", primaryKeyword: "fallout review", primaryEntity: "Fallout (American TV series)", entities: ["Fallout (American TV series)", "Ella Purnell", "Walton Goggins"] },
  { id: "austin-butler", slug: "austin-butler-movies-and-tv-shows", title: "Austin Butler Movies and TV Shows", contentType: "profile", category: "celebrity", subcategory: "profiles-careers", primaryKeyword: "austin butler movies and tv shows", primaryEntity: "Austin Butler", entities: ["Austin Butler", "Elvis (2022 film)", "Dune: Part Two", "The Bikeriders"] },
  { id: "best-scifi-tv", slug: "best-sci-fi-tv-shows-ranked", title: "Best Sci-Fi TV Shows of All Time, Ranked", contentType: "ranking list", category: "tv", subcategory: "rankings-lists", primaryKeyword: "best sci-fi tv shows", primaryEntity: "Battlestar Galactica (2004 TV series)", entities: ["Battlestar Galactica (2004 TV series)", "The Expanse (TV series)", "Black Mirror", "Severance (TV series)", "Westworld (TV series)"] },
  { id: "best-on-max", slug: "best-movies-on-max", title: "Best Movies on Max Right Now", contentType: "streaming guide", category: "streaming", subcategory: "best-of-streaming", primaryKeyword: "best movies on max", primaryEntity: "Dune (2021 film)", entities: ["Dune (2021 film)", "The Batman (film)", "Barbie (film)", "Everything Everywhere All at Once"] },
  { id: "lotr-where-watch", slug: "where-to-watch-lord-of-the-rings", title: "Where to Watch the Lord of the Rings Movies", contentType: "streaming guide", category: "streaming", subcategory: "where-to-watch", primaryKeyword: "where to watch lord of the rings", primaryEntity: "The Lord of the Rings (film series)", entities: ["The Lord of the Rings (film series)", "The Lord of the Rings: The Fellowship of the Ring"] },
  { id: "barbenheimer", slug: "barbenheimer-explained", title: "Barbenheimer Explained: How Barbie and Oppenheimer Made History", contentType: "explainer", category: "movies", subcategory: "explainers", primaryKeyword: "barbenheimer explained", primaryEntity: "Barbenheimer", entities: ["Barbenheimer", "Barbie (film)", "Oppenheimer (film)"] },
  { id: "sydney-sweeney", slug: "sydney-sweeney-movies-and-tv-shows", title: "Sydney Sweeney Movies and TV Shows", contentType: "profile", category: "celebrity", subcategory: "profiles-careers", primaryKeyword: "sydney sweeney movies and tv shows", primaryEntity: "Sydney Sweeney", entities: ["Sydney Sweeney", "Euphoria (American TV series)", "Anyone but You", "The White Lotus"] },
];
