// MANUAL FIXTURES for the legacy `node run.mjs` path (no --from-find). Production always runs --from-find;
// these exist ONLY for dev smoke-tests of the MAKE half — one per live news form that can run without FIND.
// (2026-07-03 strip: the 16 validation-era fixtures — rankings/reviews/explainers/profiles/interviews/
// streaming guides — were removed with the news-only strip; those forms no longer route.)
export const TOPICS = [
  // short inverted-pyramid celebrity NEWS
  { id: "zendaya-odyssey-news", slug: "zendaya-the-odyssey-christopher-nolan", title: "Zendaya Joins Christopher Nolan's The Odyssey", contentType: "celebrity news", formatTag: "news", category: "celebrity", subcategory: "news", primaryKeyword: "zendaya the odyssey", primaryEntity: "Zendaya", entities: ["Zendaya", "The Odyssey (2026 film)", "Christopher Nolan"], angle: "What Zendaya's casting in Christopher Nolan's epic signals for her career and the film" },
  // trade-style BOX-OFFICE report (figures grounded on TMDB worldwide/budget + OMDb domestic)
  { id: "barbie-box-office", slug: "barbie-box-office-2023", title: "Barbie Box Office: How Greta Gerwig's Hit Made History", contentType: "box office", formatTag: "box-office", category: "movies", subcategory: "box-office", primaryKeyword: "barbie box office", primaryEntity: "Barbie (film)", entities: ["Barbie (film)", "Greta Gerwig", "Margot Robbie", "Warner Bros."], angle: "Barbie's record-breaking run, the records it set, and what it meant for Warner Bros. and women directors" },
  // TRAILER preview (embed + context grounded on TMDB videos)
  { id: "superman-trailer", slug: "superman-2025-trailer-everything-to-know", title: "The Superman Trailer: Everything to Know About James Gunn's Reboot", contentType: "trailer", formatTag: "trailer", category: "movies", subcategory: "trailers", tmdbType: "movie", primaryKeyword: "superman trailer", primaryEntity: "Superman (2025 film)", entities: ["Superman (2025 film)", "James Gunn", "David Corenswet", "Rachel Brosnahan", "Nicholas Hoult"] },
  // REACTION roundup (real public X posts; FIND does not yet emit tweetIds — dev-only grounding)
  { id: "superman-reactions", slug: "superman-2025-reactions-what-fans-are-saying", title: "Superman 2025 Reactions: What Critics and Fans Are Saying", contentType: "reaction", formatTag: "reaction", category: "movies", subcategory: "reactions", primaryKeyword: "superman 2025 reactions", primaryEntity: "Superman (2025 film)", entities: ["Superman (2025 film)", "James Gunn", "David Corenswet"], tweetIds: ["1942433712928342354", "1942433464537559241", "1943486116080017514", "1994017424501281227"] },
  // AWARDS winners-list (grounded on the official Academy Awards Database cache)
  { id: "oscars-96-winners", slug: "oscars-2024-winners-96th-academy-awards", title: "Oscars 2024 Winners: Oppenheimer Sweeps the 96th Academy Awards", contentType: "awards winners", formatTag: "awards", category: "awards", subcategory: "winners", primaryKeyword: "oscars 2024 winners", primaryEntity: "96th Academy Awards", entities: ["96th Academy Awards", "Oppenheimer (film)", "Christopher Nolan", "Cillian Murphy", "Emma Stone"], angle: "Oppenheimer's seven-win sweep and the night's biggest moments" },
];
